services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: atlas-postgres
    environment:
      POSTGRES_DB: atlas
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas_secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: atlas-redis
    ports:
      - "6379:6379"

  atlas-ai:
    build:
      context: .
      dockerfile: atlas-ai/Dockerfile
    container_name: atlas-ai
    ports:
      - "50051:50051"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - POSTGRES_URL=postgresql://atlas:atlas_secret@postgres:5432/atlas
    volumes:
      - shared-repos:/tmp/atlas-repos
    depends_on:
      - postgres

  atlas-api:
    build:
      context: .
      dockerfile: atlas-api/Dockerfile
    container_name: atlas-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/atlas
      - SPRING_DATASOURCE_USERNAME=atlas
      - SPRING_DATASOURCE_PASSWORD=atlas_secret
      - SPRING_DATA_REDIS_HOST=redis
      - ATLAS_AI_GRPC_HOST=atlas-ai
      - ATLAS_AI_GRPC_PORT=50051
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    volumes:
      - shared-repos:/tmp/atlas-repos
    depends_on:
      - postgres
      - redis
      - atlas-ai

#   atlas-frontend:
#     build: ./atlas-frontend
#     container_name: atlas-frontend
#     ports:
#       - "3000:3000"
#     environment:
#       - NEXT_PUBLIC_API_URL=http://localhost:8080
#     depends_on:
#       - atlas-api

volumes:
  postgres_data:
  shared-repos:
