-- The runtime embedding model is all-MiniLM-L6-v2 (384 dimensions).
-- Existing vectors cannot be losslessly converted, so they are cleared and
-- regenerated by the next indexing run.
ALTER TABLE code_nodes
    ALTER COLUMN embedding TYPE vector(384)
    USING NULL::vector(384);
